version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3

  backend1:
    image: nginx
    expose:
      - "80"
    environment:
      - NGINX_HOST=backend1

  backend2:
    image: nginx
    expose:
      - "80"
    environment:
      - NGINX_HOST=backend2

  backend3:
    image: nginx
    expose:
      - "80"
    environment:
      - NGINX_HOST=backend3
